server:
  port: 8081
dubbo:
  application:
    name: sound-service
  registry:
    address: zookeeper://127.0.0.1:2181
  #    client: curator
  scan:
    base-packages: com.wisdom.soundservice.service.impl
  config-center:
    timeout: 100000

#数据源设置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sound?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 104361
    driver-class-name: com.mysql.cj.jdbc.Driver #Springboot2.6 用的是这个驱动类
#mybatis分页插件
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#mybatis 映射文件设置
mybatis:
  mapper-locations: classpath:com/wisdom/soundservice/dao/*.xml
  type-aliases-package: com.wisdom.weixinapp.sound.pojo