
server:
  port: 8082
dubbo:
  application:
    name: sound-web
  registry:
    address: zookeeper://127.0.0.1:2181
  #    client: curator
  scan:
    base-packages: com.wisdom.soundservice.service.impl
  config-center:
    timeout: 100000
#数据源设置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sound?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 104361
    driver-class-name: com.mysql.cj.jdbc.Driver #Springboot2.6 用的是这个驱动类
    #页面配置
    thymeleaf:
      cache: false
      encoding: UTF-8
      mode: LEGACYHTML5
  thymeleaf:
    mode: HTML5
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/